# -*- coding: utf-8 -*-
"""FaceRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e79HMYlBToJPD5LIb5A1iaasstRrgjv0
"""

!pip install cmake
!pip install dlib
!pip install face-recognition

!pip install numpy
!pip install opencv-python

import cv2
import numpy as np
import face_recognition
from google.colab.patches import cv2_imshow

imgAgn = face_recognition.load_image_file('/content/agneya.JPG')
imgAgn = cv2.cvtColor(imgAgn,cv2.COLOR_BGR2RGB)

imgTest = face_recognition.load_image_file('/content/agneyaTest.jpg')
imgTest = cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)

faceLoc = face_recognition.face_locations(imgAgn)[0]
encodeAgn = face_recognition.face_encodings(imgAgn)[0]
cv2.rectangle(imgAgn,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)

faceLocTest = face_recognition.face_locations(imgTest)[0]
encodeTest = face_recognition.face_encodings(imgTest)[0]
cv2.rectangle(imgTest,(faceLocTest[3],faceLocTest[0]),(faceLocTest[1],faceLocTest[2]),(255,0,255),2)


results = face_recognition.compare_faces([encodeAgn],encodeTest)
faceDist = face_recognition.face_distance([encodeAgn],encodeTest)
print(results, faceDist)


cv2.putText(imgTest,f'{results} {round(faceDist[0],2)}',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)


cv2_imshow(imgAgn)
cv2_imshow(imgTest)
cv2.waitKey(0)